module.exports = {
  rules: [
    {
      name: "Page",
      description:"Captures the the base div elements Magic creates from the Form",
      regex: /(?<page><div\s*novalidate[\s\S]*?>[\s\S]*?>)(?<content>[\s\S]*?)\s*<\/div>\s*<\/div>\s*~~WIZLY_EOF~~$/gm,
      templateFile: "page.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Button",
      description: "Captures all button elements created by Magic Button element, zoom or table action ",
      regex: /(?<button><button[\s\S]*?>)(?<content>[\s\S]*?)<\/button>/gm,
      templateFile: "button.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Image",
      description: "Captures the image tag and wrapping div created from Magic Image element",
      regex: /(<div[\s\S]*?>)\s*(?<imgage><img[\s\S]*?\/>)\s*<\/div>/gm,
      templateFile: "image.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Tab wrapping div",
      description: "Removes the wrapping div of a tab group, will only work if you use smartTabMatcher",
      regex: /<div>\s*(?<content><mat-tab-group[\s\S]*?<\/mat-tab-group>)\s*<\/div>/gm,
      replacement: "$<content>",
      active: true,
      activeWhen: 'smartTabMatcher',
      filePattern: "*.html",
    },
    {
      name: "Tab",
      description: "Captures the tab-group created by Magic Tab element, content is not handeled automaticly",
      regex: /(?<matTabGroup><mat-tab-group[\s\S]*?>)\s*(?<matTab><mat-tab[\s\S]*?<\/mat-tab>)\s*<\/mat-tab-group>/gm,
      templateFile: "tab.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Subforms",
      description: "Captures the magic-subform tag and its wrapping mat-card created by Magic Subform element",
      regex: /(?<matCard><mat-card)[\s\S]*?>\s*(?<subform><magic-subform[\s\S]*?<\/magic-subform>)\s*<\/mat-card>/gm,
      templateFile: "subform.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Card",
      description: "Captures the mat-card element created by Magic Group element`, the rule should be placed after subform",
      regex: /(?<card><mat-card[\s\S]*?>\r?\n)(?<content>[\s\S]*?)<\/mat-card>/gm,
      templateFile: "card.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Labels",
      description: "Captures the label tag created by Magic Label element",
      regex: /(?<label><label[\s\S]*?>)(?<content>[\s\S]*?)<\/label>/gm,
      templateFile: "label.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Flex row",
      description: "Replace inline styling of flex row with bootstrap utility class",
      regex: /<div style="display: flex; flex-direction: row">/gm,
      templateFile: "flex-row.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Input - Checkbox",
      description: "Captures the mat-input tag and wrapping div created by Magic Check Box element",
      regex: /<div>\s*(?<input><mat-checkbox[\s\S]*?>)(?<content>[\s\S]*?)<\/mat-checkbox>[\s\S]*?<\/div>/gm,
      templateFile: "checkbox.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Editable Combo",
      description: "Captures the editable-combo tag and wrapping div created by Magic Combo Box element with property Editable = true",
      regex: /<div>\s*(?<input><editable-combo[\s\S]*?<\/editable-combo>)[\s\S]*?<\/div>/gm,
      templateFile: "editable-combo.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Select",
      description: "Captures the mat-select tag and wrapping div and mat-form-field created by Magic Combo Box element with property Editable = false",
      regex: /<div>\s*(?<formField><mat-form-field[\s\S]*?)(?<input><mat-select[\s\S]*?<\/mat-select>)\s*<\/mat-form-field>[\s\S]*?<\/div>/gm,
      templateFile: "select.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Selectionlist",
      description: "Captures the mat-selection-list tag and wrapping div created by Magic List Box with element",
      regex: /<div>\s*(?<matSelectionList><mat-selection-list[\s\S]*?>)[\s\S]*?<\/mat-selection-list>\s*<mgError[\s\S]*?<\/mgError>\s*<\/div>/gm,
      templateFile: "selectionlist.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Input - Radio",
      description: "Captures the mat-radio-group created by Magic Radio Button element",
      regex: /(?<matRadioGroup><mat-radio-group[\s\S]*?>)[\s\S]*?<\/mat-radio-group>\s*<mgError[\s\S]*?<\/mgError>/gm,
      templateFile: "radio.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Input",
      description: "Captures all matInput (text, date, time, number, autocomplete) with optional zoom button created by Magic Edit element",
      regex: /<div>\s*(?<formField><mat-form-field\b[^>]*>)\s*(<div>)?\s*(?<input><input[\s\S]*?matInput\b[^>]*>)[\s\S]*?<\/mat-form-field>\s*(?<zoom><button[\s\S]*?>[\s\S]*?<\/button>)?\s*[\s\S]*?<\/div>/gm,
      templateFile: "input-base.ejs",
      active: true,
      filePattern: "*.html"
    },
    {
      name: "Table",
      description: "Captures mat-table tag created by Magic Table element",
      regex: /(?<table><div[^>]*>)\s*<mat-table[\s\S]*?>\s*(?<content>[\s\S]*?)\s*<mat-header-row[\s\S]*?<\/mat-paginator>\s*<\/div>/gm,
      templateFile: "table.ejs",
      active: true,
      filePattern: "*.html",
    },
    {
      name: "Table Column",
      description: "Captures all matColumnDef created by Magic Table element",
      regex: /<ng-container\s*\[magic\]="(?<magic>.*?)"\s*\[matColumnDef\]="\k<magic>"\s*>\s*<mat-header-cell[\s\S]*?<\/mat-header-cell>\s*<mat-cell\b[^>]*magicMark="magicTableRowContainer"[^>]*>\s*<div\b[^>]*>\s*<div\b[^>]*>\s*(?<content>[\s\S]*?)\s*<\/div>\s*<\/div>\s*<\/mat-cell>\s*<\/ng-container>/gm,
      templateFile: "table-column.ejs",
      active: true,
      filePattern: "*.html",
    }
  ],
};