export type MagicColorValueKind = 'rgb' | 'system';
export type MagicColorValue = {
    original: string;
    scssValue: string;
    kind: MagicColorValueKind;
    systemIndex?: number;
    systemName?: string;
};

export type MagicColorEntry = {
    index: number;
    name: string;
    rawForeground: string;
    rawBackground: string;
    foreground: MagicColorValue;
    background: MagicColorValue;
    transparentBackground: boolean;
    rawFlag1: string;
    rawFlag2: string;
};

const magicSystemColorMap: Record<number, { name: string; css: string }> = {
    0: { name: 'Scrollbar', css: '#c8c8c8' },
    1: { name: 'Desktop', css: '#000000' },
    2: { name: 'ActiveCaption', css: 'Highlight' },
    3: { name: 'InactiveCaption', css: '#808080' },
    4: { name: 'Menu', css: 'ButtonFace' },
    5: { name: 'Window', css: 'Canvas' },
    6: { name: 'WindowFrame', css: '#646464' },
    7: { name: 'MenuText', css: 'ButtonText' },
    8: { name: 'WindowText', css: 'CanvasText' },
    9: { name: 'CaptionText', css: 'CanvasText' },
    10: { name: 'ActiveBorder', css: 'ButtonBorder' },
    11: { name: 'InactiveBorder', css: 'ButtonFace' },
    12: { name: 'AppWorkspace', css: '#ababab' },
    13: { name: 'Highlight', css: 'Highlight' },
    14: { name: 'HighlightText', css: 'HighlightText' },
    15: { name: 'Control', css: 'ButtonFace' },
    16: { name: 'ControlDark', css: '#808080' },
    17: { name: 'GrayText', css: 'GrayText' },
    18: { name: 'ControlText', css: 'ButtonText' },
    19: { name: 'InactiveCaptionText', css: 'GrayText' },
    20: { name: 'ControlLightLight', css: 'ButtonHighlight' },
    21: { name: 'ControlDarkDark', css: '#404040' },
    22: { name: 'InfoText', css: 'InfoText' },
    23: { name: 'InfoBackground', css: 'InfoBackground' },
    24: { name: 'HotLight', css: 'LinkText' },
    25: { name: 'MenuHighlight', css: 'Highlight' },
    26: { name: 'GradientActiveCaption', css: 'Highlight' },
    27: { name: 'GradientInactiveCaption', css: 'ButtonFace' },
};

function quoteScssString(text: string): string {
    return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export function parseMagicColorValue(rawValue: string): MagicColorValue {
    const raw = rawValue.trim().toUpperCase();
    if (!/^[0-9A-F]{8}$/.test(raw)) {
        return {
            original: raw,
            scssValue: 'transparent',
            kind: 'rgb',
        };
    }

    const unsigned = Number.parseInt(raw, 16);
    const signed = unsigned > 0x7fffffff ? unsigned - 0x100000000 : unsigned;
    if (signed < 0) {
        const systemIndex = (-signed) - 1;
        const mapped = magicSystemColorMap[systemIndex];
        return {
            original: raw,
            scssValue: mapped?.css ?? 'Canvas',
            kind: 'system',
            systemIndex,
            systemName: mapped?.name ?? `SystemColor${systemIndex}`,
        };
    }

    // Magic stores colors as a Windows COLORREF (00BBGGRR), so the byte order is reversed for CSS (#rrggbb).
    const blue = raw.slice(2, 4);
    const green = raw.slice(4, 6);
    const red = raw.slice(6, 8);
    return {
        original: raw,
        scssValue: `#${red}${green}${blue}`.toLowerCase(),
        kind: 'rgb',
    };
}

export function parseMagicColorFile(content: string): MagicColorEntry[] {
    const entries: MagicColorEntry[] = [];
    const lines = content.split(/\r?\n/);
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) { continue; }

        const parts = trimmed.split(',').map((part) => part.trim());
        if (parts.length < 5) { continue; }

        const name = parts[0] || `Color ${entries.length + 1}`;
        const rawForeground = parts[1] || '00000000';
        const rawBackground = parts[2] || '00000000';
        const rawFlag1 = parts[3] || '0';
        const rawFlag2 = parts[4] || '0';
        const transparentBackground = rawFlag1 === '1';

        entries.push({
            index: entries.length + 1,
            name,
            rawForeground,
            rawBackground,
            foreground: parseMagicColorValue(rawForeground),
            background: parseMagicColorValue(rawBackground),
            transparentBackground,
            rawFlag1,
            rawFlag2,
        });
    }
    return entries;
}

export function renderMagicColorVarsScss(entries: MagicColorEntry[]): string {
    const lines: string[] = [];
    lines.push('// Generated by Wizly: Import Magic Color File (SCSS)');
    lines.push('// The numbering matches the row order in the Magic color file.');
    lines.push('// System colors are mapped to CSS system colors or close fallback values where needed.');
    lines.push("// Use magic.fg(5) and magic.bg(5) in component SCSS, or magic.$colors for the full map.");
    lines.push("@use 'sass:map';");
    lines.push('');

    lines.push('$colors: (');
    for (const entry of entries) {
        lines.push(`  // ${entry.index}: ${entry.name}`);
        if (entry.foreground.kind === 'system' && entry.foreground.systemName) {
            lines.push(`  // Foreground ${entry.rawForeground} -> ${entry.foreground.systemName}`);
        }
        if (!entry.transparentBackground && entry.background.kind === 'system' && entry.background.systemName) {
            lines.push(`  // Background ${entry.rawBackground} -> ${entry.background.systemName}`);
        } else if (entry.transparentBackground) {
            lines.push(`  // Background ${entry.rawBackground} skipped because flag1 indicates transparency.`);
        }
        lines.push(`  ${entry.index}: (`);
        lines.push(`    name: ${quoteScssString(entry.name)},`);
        lines.push(`    foreground: ${entry.foreground.scssValue},`);
        lines.push(`    background: ${entry.transparentBackground ? 'transparent' : entry.background.scssValue},`);
        lines.push(`    transparent: ${entry.transparentBackground ? 'true' : 'false'},`);
        lines.push(`    source-foreground: ${quoteScssString(entry.rawForeground)},`);
        lines.push(`    source-background: ${quoteScssString(entry.rawBackground)},`);
        lines.push('  ),');
    }
    lines.push(');');
    lines.push('');
    lines.push('@function entry($nr) {');
    lines.push('  @if not map.has-key($colors, $nr) {');
    lines.push('    @error "Magic color #{$nr} does not exist in the imported color file.";');
    lines.push('  }');
    lines.push('  @return map.get($colors, $nr);');
    lines.push('}');
    lines.push('');
    lines.push('@function fg($nr) {');
    lines.push('  @return map.get(entry($nr), foreground);');
    lines.push('}');
    lines.push('');
    lines.push('@function bg($nr) {');
    lines.push('  @return map.get(entry($nr), background);');
    lines.push('}');
    return `${lines.join('\n').trimEnd()}\n`;
}

// Marker that tells a current utilities file apart from the older per-entry format.
export const magicColorUtilitiesMarker = 'magic.$colors';

// The map lives in abstracts/ (7-1: Sass tools without CSS output). A utilities file without this path is outdated.
export const magicColorsUsePath = '../abstracts/magic-colors';

export function renderMagicColorUtilitiesScss(): string {
    const lines: string[] = [];
    lines.push('// Generated by Wizly: Import Magic Color File (SCSS)');
    lines.push('// Each class keeps the Magic color number so existing Magic references stay recognizable.');
    lines.push('// The classes come from abstracts/_magic-colors.scss. A new import only rewrites that file, so changes here are kept.');
    lines.push("@use 'sass:map';");
    lines.push(`@use '${magicColorsUsePath}' as magic;`);
    lines.push('');
    lines.push(`@each $nr, $c in ${magicColorUtilitiesMarker} {`);
    lines.push('  .magic-color-#{$nr} {');
    lines.push('    color: map.get($c, foreground);');
    lines.push('    @if not map.get($c, transparent) {');
    lines.push('      background-color: map.get($c, background);');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    return `${lines.join('\n')}\n`;
}
