export type MagicColorValueKind = 'rgb' | 'system';
export type MagicColorValue = {
    original: string;
    scssValue: string;
    kind: MagicColorValueKind;
    systemIndex?: number;
    systemName?: string;
};

export type MagicColorEntry = {
    index: number;
    name: string;
    rawForeground: string;
    rawBackground: string;
    foreground: MagicColorValue;
    background: MagicColorValue;
    transparentBackground: boolean;
    rawFlag1: string;
    rawFlag2: string;
};

const magicSystemColorMap: Record<number, { name: string; css: string }> = {
    0: { name: 'Scrollbar', css: '#c8c8c8' },
    1: { name: 'Desktop', css: '#000000' },
    2: { name: 'ActiveCaption', css: 'Highlight' },
    3: { name: 'InactiveCaption', css: '#808080' },
    4: { name: 'Menu', css: 'ButtonFace' },
    5: { name: 'Window', css: 'Canvas' },
    6: { name: 'WindowFrame', css: '#646464' },
    7: { name: 'MenuText', css: 'ButtonText' },
    8: { name: 'WindowText', css: 'CanvasText' },
    9: { name: 'CaptionText', css: 'CanvasText' },
    10: { name: 'ActiveBorder', css: 'ButtonBorder' },
    11: { name: 'InactiveBorder', css: 'ButtonFace' },
    12: { name: 'AppWorkspace', css: '#ababab' },
    13: { name: 'Highlight', css: 'Highlight' },
    14: { name: 'HighlightText', css: 'HighlightText' },
    15: { name: 'Control', css: 'ButtonFace' },
    16: { name: 'ControlDark', css: '#808080' },
    17: { name: 'GrayText', css: 'GrayText' },
    18: { name: 'ControlText', css: 'ButtonText' },
    19: { name: 'InactiveCaptionText', css: 'GrayText' },
    20: { name: 'ControlLightLight', css: 'ButtonHighlight' },
    21: { name: 'ControlDarkDark', css: '#404040' },
    22: { name: 'InfoText', css: 'InfoText' },
    23: { name: 'InfoBackground', css: 'InfoBackground' },
    24: { name: 'HotLight', css: 'LinkText' },
    25: { name: 'MenuHighlight', css: 'Highlight' },
    26: { name: 'GradientActiveCaption', css: 'Highlight' },
    27: { name: 'GradientInactiveCaption', css: 'ButtonFace' },
};

function quoteScssString(text: string): string {
    return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

export function parseMagicColorValue(rawValue: string): MagicColorValue {
    const raw = rawValue.trim().toUpperCase();
    if (!/^[0-9A-F]{8}$/.test(raw)) {
        return {
            original: raw,
            scssValue: 'transparent',
            kind: 'rgb',
        };
    }

    const unsigned = Number.parseInt(raw, 16);
    const signed = unsigned > 0x7fffffff ? unsigned - 0x100000000 : unsigned;
    if (signed < 0) {
        const systemIndex = (-signed) - 1;
        const mapped = magicSystemColorMap[systemIndex];
        return {
            original: raw,
            scssValue: mapped?.css ?? 'Canvas',
            kind: 'system',
            systemIndex,
            systemName: mapped?.name ?? `SystemColor${systemIndex}`,
        };
    }

    return {
        original: raw,
        scssValue: `#${raw.slice(-6).toLowerCase()}`,
        kind: 'rgb',
    };
}

export function parseMagicColorFile(content: string): MagicColorEntry[] {
    const entries: MagicColorEntry[] = [];
    const lines = content.split(/\r?\n/);
    for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) { continue; }

        const parts = trimmed.split(',').map((part) => part.trim());
        if (parts.length < 5) { continue; }

        const name = parts[0] || `Color ${entries.length + 1}`;
        const rawForeground = parts[1] || '00000000';
        const rawBackground = parts[2] || '00000000';
        const rawFlag1 = parts[3] || '0';
        const rawFlag2 = parts[4] || '0';
        const transparentBackground = rawFlag1 === '1';

        entries.push({
            index: entries.length + 1,
            name,
            rawForeground,
            rawBackground,
            foreground: parseMagicColorValue(rawForeground),
            background: parseMagicColorValue(rawBackground),
            transparentBackground,
            rawFlag1,
            rawFlag2,
        });
    }
    return entries;
}

export function renderMagicColorVarsScss(entries: MagicColorEntry[]): string {
    const lines: string[] = [];
    lines.push('// Generated by Wizly: Import Magic Color File (SCSS)');
    lines.push('// The numbering matches the row order in the Magic color file.');
    lines.push('// System colors are mapped to CSS system colors or close fallback values where needed.');
    lines.push('');

    for (const entry of entries) {
        lines.push(`// ${entry.index}: ${entry.name}`);
        if (entry.foreground.kind === 'system' && entry.foreground.systemName) {
            lines.push(`// Foreground ${entry.rawForeground} -> ${entry.foreground.systemName}`);
        }
        if (!entry.transparentBackground && entry.background.kind === 'system' && entry.background.systemName) {
            lines.push(`// Background ${entry.rawBackground} -> ${entry.background.systemName}`);
        } else if (entry.transparentBackground) {
            lines.push(`// Background ${entry.rawBackground} skipped because flag1 indicates transparency.`);
        }
        lines.push(`$magic-color-${entry.index}-name: ${quoteScssString(entry.name)};`);
        lines.push(`$magic-color-${entry.index}-foreground: ${entry.foreground.scssValue};`);
        lines.push(`$magic-color-${entry.index}-background: ${entry.transparentBackground ? 'transparent' : entry.background.scssValue};`);
        lines.push(`$magic-color-${entry.index}-transparent: ${entry.transparentBackground ? 'true' : 'false'};`);
        lines.push(`$magic-color-${entry.index}-source-foreground: ${quoteScssString(entry.rawForeground)};`);
        lines.push(`$magic-color-${entry.index}-source-background: ${quoteScssString(entry.rawBackground)};`);
        lines.push('');
    }

    lines.push('$wizly-magic-colors: (');
    for (const entry of entries) {
        lines.push(`  ${entry.index}: (`);
        lines.push(`    name: $magic-color-${entry.index}-name,`);
        lines.push(`    foreground: $magic-color-${entry.index}-foreground,`);
        lines.push(`    background: $magic-color-${entry.index}-background,`);
        lines.push(`    transparent: $magic-color-${entry.index}-transparent,`);
        lines.push(`    source-foreground: $magic-color-${entry.index}-source-foreground,`);
        lines.push(`    source-background: $magic-color-${entry.index}-source-background,`);
        lines.push('  ),');
    }
    lines.push(');');
    return `${lines.join('\n').trimEnd()}\n`;
}

export function renderMagicColorUtilitiesScss(entries: MagicColorEntry[]): string {
    const lines: string[] = [];
    lines.push("// Generated by Wizly: Import Magic Color File (SCSS)");
    lines.push("// Each class keeps the Magic color number so existing Magic references stay recognizable.");
    lines.push("@use '../vars/magic-colors' as magic;");
    lines.push('');

    for (const entry of entries) {
        lines.push(`// ${entry.index}: ${entry.name}`);
        lines.push(`.magic-color-${entry.index} {`);
        lines.push(`  color: magic.$magic-color-${entry.index}-foreground;`);
        if (!entry.transparentBackground) {
            lines.push(`  background-color: magic.$magic-color-${entry.index}-background;`);
        }
        lines.push('}');
        lines.push('');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}
